version: '3.9'
services:
  db:
    image: postgres:13
    container_name: currency_exchange_db
    environment:
      POSTGRES_DB: currency_exchange
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - currencyexchange-network

volumes:
  postgres-data:

networks:
  currencyexchange-network:
